### ISSUE TITLE
Complex Insert error

### ISSUE THREAD

**Issue by orienweb** [khoih-prog/MySQL_MariaDB_Generic#10]
Hello.
I am trying to access mariadb with this `code:

`#include "defines.h"
#include "Credentials.h"
#include <MySQL_Generic.h>
#define USING_HOST_NAME     true
#if USING_HOST_NAME
  // Optional using hostname, and Ethernet built-in DNS lookup
  char server[] = "www.prueba.net"; // change to your server's hostname/URL
#else
  IPAddress server(192, 168, 0, 176);
#endif
uint16_t server_port = 3306; //5698; 
char default_database[] = "*****";           //"test_arduino";
char default_table[]    = "*******";         //"test_arduino";
// Sample query
// char INSERT_DATA[] = "INSERT INTO %s.%s (message, sensor_num, value) VALUES ('%s',%d,%s)";
char INSERT_DATA[] = "INSERT INTO %s.%s (numero_granja, nombre, humedad_tierra, humedad_hambiente, temperatura) VALUES ('%s','%s','%s','%s','%s')";
char query[200]; // cambiado de 128 a 200
char temperature[10];
MySQL_Connection conn((Client *)&client);
#if !( ESP32 || ESP8266 || defined(CORE_TEENSY) || defined(STM32F1) || defined(STM32F2) || defined(STM32F3) || defined(STM32F4) || defined(STM32F7) || ( defined(ARDUINO_ARCH_RP2040) && !defined(ARDUINO_ARCH_MBED) ) ) 
char *dtostrf(double val, signed char width, unsigned char prec, char *sout)
{
  char fmt[20];
  sprintf(fmt, "%%%d.%df", width, prec);
  sprintf(sout, fmt, val);
  return sout;
}
#endif
void setup()
{
  Serial.begin(115200);
  while (!Serial);
  MYSQL_DISPLAY1("\nStarting Complex_Insert_WiFi on", BOARD_NAME);
  MYSQL_DISPLAY(MYSQL_MARIADB_GENERIC_VERSION);
  // Remember to initialize your WiFi module
#if ( USING_WIFI_ESP8266_AT  || USING_WIFIESPAT_LIB ) 
  #if ( USING_WIFI_ESP8266_AT )
    MYSQL_DISPLAY("Using ESP8266_AT/ESP8266_AT_WebServer Library");
  #elif ( USING_WIFIESPAT_LIB )
    MYSQL_DISPLAY("Using WiFiEspAT Library");
  #endif
  // initialize serial for ESP module
  EspSerial.begin(115200);
  // initialize ESP module
  WiFi.init(&EspSerial);
  MYSQL_DISPLAY(F("WiFi shield init done"));
  // check for the presence of the shield
  if (WiFi.status() == WL_NO_SHIELD)
  {
    MYSQL_DISPLAY(F("WiFi shield not present"));
    // don't continue
    while (true);
  }
#endif
  // Begin WiFi section
  MYSQL_DISPLAY1("Connecting to", ssid);
  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) 
  {
    delay(500);
    MYSQL_DISPLAY0(".");
  }
  // print out info about the connection:
  MYSQL_DISPLAY1("Connected to network. My IP address is:", WiFi.localIP());
  MYSQL_DISPLAY3("Connecting to SQL Server @", server, ", Port =", server_port);
  MYSQL_DISPLAY5("User =", user, ", PW =", password, ", DB =", default_database);
}
void runInsert()
{
  // Initiate the query class instance
  MySQL_Query query_mem = MySQL_Query(&conn);

  if (conn.connected())
  {
    // Save
    dtostrf(50.125, 1, 1, temperature);
     sprintf(query, INSERT_DATA, default_database, default_table, "7", "prueba", "23", "25","5");//temperature);
    //sprintf(query, INSERT_DATA,"7", "prueba", "23", "25","5");//temperature);
    // Execute the query
    MYSQL_DISPLAY(query);

    // KH, check if valid before fetching
    if ( !query_mem.execute(query) )
    {
      MYSQL_DISPLAY("Complex Insert error");
    }
    else
    {
      MYSQL_DISPLAY("Complex Data Inserted.");
    }
  }
  else
  {
    MYSQL_DISPLAY("Disconnected from Server. Can't insert.");
  }
}

void loop()
{
  MYSQL_DISPLAY("Connecting...");
  
  //if (conn.connect(server, server_port, user, password))
  if (conn.connectNonBlocking(server, server_port, user, password) != RESULT_FAIL)
  {
    delay(500);
    runInsert();
    conn.close();                     // close the connection
  } 
  else 
  {
    MYSQL_DISPLAY("\nConnect failed. Trying again on next iteration.");
  }

  MYSQL_DISPLAY("\nSleeping...");
  MYSQL_DISPLAY("================================================");
 
  delay(60000);
}`

I manage to connect but the problem comes when I am going to execute the query that returns the following message:

Starting Complex_Insert_WiFi on ESP8266_GENERIC
MySQL_MariaDB_Generic v1.5.1
Connecting to Nextfibra_C90D40
.......Connected to network. My IP address is: *.*.*.*
Connecting to SQL Server @ www.pruebas.net , Port = 3306
User = ***** , PW = **** , DB = ***
Connecting...
[SQL] Connecting to Server: ****** , Port =  3306
[SQL] Connect OK. Try reading packets
[SQL] Try parsing packets
[SQL] Try send_authentication packets
[SQL] Writing this_buffer, size_send = 73
[SQL] Connected. Server Version = 5.5.5-10.4.21-MariaDB
INSERT INTO orienweb_controlfarm.granja (numero_granja, nombre, humedad_tierra, humedad_hambiente, temperatura) VALUES ('7','prueba','23','25','5')
Complex Insert error
[SQL] Disconnected

Where this error?

Thank you.

**Comment by khoih-prog** [comment]
It's difficult to guess **what's wrong with your modified code and/or MariaDB database.**

Normally, in this situation, you have to

1. Turn on debug mode by changing in `defined.h`

```
// Debug Level from 0 to 4
#define _MYSQL_LOGLEVEL_      4
```

then have more info about what's wrong with your code / database

2. Create a local database and/or **test the INSERT manually** to see if your database accepts

```
INSERT INTO orienweb_controlfarm.granja (numero_granja, nombre, humedad_tierra, humedad_hambiente, temperatura) VALUES ('7','prueba','23','25','5')
```

There are too many scenarios, and only you can find out and fix.

I'm sorry I won't spend any more time in this basic usage. It's better if you still having issue, post for help in [Arduino Forum](https://forum.arduino.cc/).
