### ISSUE TITLE
GPRS example.

### ISSUE THREAD

**Issue by EliasA97** [khoih-prog/MySQL_MariaDB_Generic#12]
Hello, could you make an example for gsm modules like the SIM800?

**Comment by khoih-prog** [comment]
Hi,

Sorry that this library currently doesn't support the nearly-obsolete GSM / GPRS.

If there are many more requests and certainly if time permitted, I possibly will rethink and support GSM / GPRS and/or NB.

Have a look at my other [**GSM_Generic** library](https://github.com/khoih-prog/GSM_Generic) to see if you can use it. For example, using [**GsmWebClient**](https://github.com/khoih-prog/GSM_Generic/tree/main/examples/GsmWebClient) to send data to another board running [**GsmWebServer**](https://github.com/khoih-prog/GSM_Generic/tree/main/examples/GsmWebServer), then the latter board (running as `GsmWebServer`) retransmits data to MySQL_MariaDB database, etc.

Good Luck,
