### ISSUE TITLE
ESP8288

### ISSUE THREAD

**Issue by mgaman** [khoih-prog/MySQL_MariaDB_Generic#23]
The Readme refers a few times to the ESP8288. I have tried, but failed, to discover what chip this is so I am confused. Is there actually an ESP8288 or is this just a typo?
Googling ESP8288 usually comes up with info relevant to the ESP8266.

**Comment by khoih-prog** [comment]
Thanks for spotting the typo. The correct info is ESP8266. Fixed in master and in next release.
