### ISSUE TITLE
Aborted connection in the MariaDB log

### ISSUE THREAD

**Issue by urkelbundy** [khoih-prog/MySQL_MariaDB_Generic#25]
Hi,

In the MariaDB log I see the following messages:
[Warning] Aborted connection 822 to db: 'test' user: 'test' host: '192.168.1.116' (Got an error reading communication packets)
There are tons of these messages as there are 10+ esp8266 modules sending INSERT queries

At first I thought it was my code but even with the example code Basic_Insert_WiFi the same message appears in the log.

When I log the queries this is what MariaDB receives:
220911 12:08:49	   822 Connect	test@192.168.1.116 on test using TCP/IP
220911 12:08:50	   822 Query	INSERT INTO test.test (message) VALUES ('Hello, esp8266!')

The query is applied to the database test but the log is filling quickly with 10+ esp8266 modules sending INSERT queries to MariaDB
So it looks okay but why is there a warning in the MariaDB log?

I use the MariaDB docker image as the database server
Using phpadmin on this database server works fine. No warnings in the log
Grafana also no warnings in the log.
A python3 script on an odroid computer also doesn't produce these warnings when sending INSERT queries.

What exactly is being sent to the database by "query_mem.execute()" in the example code? Some strange characters maybe?

**Comment by khoih-prog** [comment]
Hi @urkelbundy 

Thanks for your interest in the library.

However, I couldn't duplicate the issue and have no issue here. Check your code, installation, etc. or try with the `mysql` database to see if OK.

I'm closing the issue now, and won't reopen until a bug is proven.

Good Luck,
