### ISSUE TITLE
Connect - Access denied problem

### ISSUE THREAD

**Issue by xLoffy** [khoih-prog/MySQL_MariaDB_Generic#4]
Arduino IDE version: 1.8.13
Arduino AVR Version: 1.8.3
arduino MEGA 2560
MySQL version: 8.0.23
Library version: 1.0.2.
Ubuntu 20.04

I created mysql user, set mysql_native_password. Connection from PC work, like this:
_**loffy@homenas:~$ mysql -uarduino -pArduino_123 -h10.0.0.10 --port=3306**_
**mysql: [Warning] Using a password on the command line interface can be insecure.**
**Welcome to the MySQL monitor.  Commands end with ; or \g.**
**Your MySQL connection id is 21**
**Server version: 8.0.23 MySQL Community Server - GPL**

**Copyright (c) 2000, 2021, Oracle and/or its affiliates.**

_**mysql> SELECT User, Host FROM mysql.user;**_
**+------------------+-----------+**
**| User             | Host      |**
**+------------------+-----------+**
**| arduino          | %         |**
**| mysql.infoschema | localhost |**
**| mysql.session    | localhost |**
**| mysql.sys        | localhost |**
**| root             | localhost |**
**+------------------+-----------+**
**5 rows in set (0.00 sec)**

I used example “Connect” from the library, I changed only ip and psw, like this:

**IPAddress server_addr(10, 0, 0, 10);**
**uint16_t server_port =3306;**
**char user[]     = "arduino";              // MySQL user login username**
**char password[] = "Arduino_123";          // MySQL user login password**

________________________________
Log from serial monitor:
21:03:14.721 -> Starting Connect on AVR Mega using ENC28J60/UIPEthernet Library
21:03:14.721 -> [SQL] =========================
21:03:14.721 -> [SQL] Default SPI pinout:
21:03:14.721 -> [SQL] MOSI: 51
21:03:14.721 -> [SQL] MISO: 50
21:03:14.721 -> [SQL] SCK: 52
21:03:14.721 -> [SQL] SS: 53
21:03:14.721 -> [SQL] =========================
21:03:14.721 -> [SQL] Unknown board setCsPin: 10
21:03:14.774 -> [SQL] =========================
21:03:14.774 -> [SQL] Currently Used SPI pinout:
21:03:14.774 -> [SQL] MOSI: 51
21:03:14.774 -> [SQL] MISO: 50
21:03:14.774 -> [SQL] SCK: 52
21:03:14.774 -> [SQL] SS: 53
21:03:14.774 -> [SQL] =========================
21:03:14.774 -> Using mac index = 15
21:03:14.774 -> Connected! IP address: 10.0.0.19
21:03:14.774 -> Connecting to SQL Server @ 10.0.0.10, Port = 3306
21:03:14.821 -> User = arduino, PW = Arduino_123
21:03:14.821 -> Connecting...
21:03:14.821 -> [SQL] Connecting to Server: 10.0.0.10 , Port =  3306
21:03:16.225 -> [SQL] Connect OK. Try reading packets
21:03:16.526 -> [SQL] MySQL_Packet::wait_for_bytes: OK, Num bytes=  78
21:03:16.526 -> [SQL] MySQL_Packet::read_packet: packet_len=  74
21:03:16.579 -> [SQL] MySQL_Packet::read_packet: First time allocate buffer, size =  78
21:03:16.579 -> [SQL] MySQL_Packet::read_packet: exit
21:03:16.579 -> [SQL] Try parsing packets
21:03:16.579 -> [SQL] Try send_authentication packets
21:03:17.482 -> [SQL] MySQL_Packet::wait_for_bytes: OK, Num bytes=  79
21:03:17.482 -> [SQL] MySQL_Packet::read_packet: packet_len=  75
21:03:17.482 -> [SQL] MySQL_Packet::read_packet: Reallocate buffer, size =  79
21:03:17.529 -> [SQL] MySQL_Packet::read_packet: exit
21:03:17.529 -> [SQL] MySQL_Packet::get_packet_type: packet type=  255
21:03:17.529 -> [SQL] MySQL_Packet::get_packet_type: packet type= MYSQL_ERROR_PACKET
21:03:17.529 -> [SQL] Error:  75  = 
21:03:17.529 -> Access denied for user 'arduino'@'10.0.0.19' (using password: YES).
21:03:17.529 -> 
21:03:17.529 -> Connect failed. Trying again on next iteration. 
__________________________

In the log from mysql I see:
2021-02-12T23:20:47.408779Z 269 [Note] [MY-010926] [Server] Access denied for user 'arduino'@'10.0.0.19' (using password: YES)

So, communication is OK, User and Password are identical as from PC, but **Access denied**. What did I forget? I'm new to mysql and I'm probably doing some stupid mistake, but I can't make any progress  .

Thanks for help.

**Comment by khoih-prog** [comment]
You have to **grant correct access/privileges to other host / users,** then test by **using another computer to login to MySQL**, instead of login locally.

Have a look at [**Access Control and Account Management**](https://dev.mysql.com/doc/refman/8.0/en/access-control.html).

If you still can't solve the issue, you have to post issue on the MySQL-related forum to ask for help.

As this issue has **nothing to do** with the library, I'm afraid I don't have time to help you further with the basic MySQL operation.

Good Luck,
