### ISSUE TITLE
Ethernet shield W5500 reset

### ISSUE THREAD

**Issue by gianfry60** [khoih-prog/MySQL_MariaDB_Generic#5]
I'm trying to make a sketch to perform a hardware reset of the W5500 ethernet shield. I need this to recover the status of hide which in some cases is the shield. I inserted a pinout on arduino and connected this to the shield of the W5500. So far everything is fine the card will reset and I can again ping from the network. After the reset, however, the MySQL connector is no longer able to connect to the server. Can you help me? I put the sketch I am using for the tests on my repository. In the repository I have also inserted the output of the serial monitor with debugging at the maximum level.
The repository is: https://github.com/gianfry60/MySQL_MariaDB_Generic_Reset_ETH
Thank you

**Comment by khoih-prog** [comment]
> After the reset, however, the MySQL connector is no longer able to connect to the server. 

You have to reset the board, not just the Ethernet. I also don't understand why you need to do that. If you're afraid of board hanging, just write some kind of WDT to reset the whole board.

---

The [**MySQL_MariaDB_Generic**](https://github.com/khoih-prog/MySQL_MariaDB_Generic) needs complicated authentication between server and client before every successful connection. You can not just reset the Ethernet board, destroying all stored authentication data and expect normal working scenario.

You certainly can achieve that unnecessary ETH reset by rewriting the library (Ethernet as well as this library), but I suggest not to and I won't spend time to do that.
